# -*- coding: utf-8 -*-
"""CIE-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZmG0-hE6k5qScUyTX3r4HyCKf1F4iNXl
"""

import pandas as pd
data = pd.read_csv("/content/titanic.csv")
df=pd.DataFrame(data)
print(df)

data.describe()

data.head(5)

data.info()

data.isnull().sum()

data.duplicated()

data.shape

data.dtypes

data['Pclass'].unique()

import pandas as pd
import matplotlib.pyplot as plt
data['Survived'] = data['Survived'].replace({1: 'survived', 0: 'not survived'})
print(data['Survived'])
grouped_data = data.groupby(['Survived', 'Pclass']) ['PassengerId']. count().unstack()
grouped_data.plot(kind='bar', figsize=(10, 6))
plt.title('Survival Counts by Pclass')
plt.xlabel('Survival')
plt.ylabel('Count')
plt.legend(title='Pclass')
plt.show()

df=data = data.isnull().sum()
print(df)
p_age = data.fillna(data.mean(numeric_only=True))
print(p_age)

import pandas as pd
df=pd.read_csv("/content/titanic.csv")
df.head(10)
from scipy import stats
age_mean=df['Age'].mean()
age_median=df['Age'].median()
age_mode=statistics.mode (df['Age'].mode())
fare_mean=df['Fare'].mean()
fare_median=df['Fare'].median()
fare_mode=statistics.mode (df['Fare'].mode())
print("mean of age is",age_mean)
print("median of age is",age_median)
print("mode of age is",age_mode)
print("mean of fare is",fare_mean)
print("median of fare is",fare_median)
print("mode of fare is",fare_mode)

from scipy import stats
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(4,6))
sns.boxplot(y=df['Fare'])
plt.title("Box plot of outliers")
plt.show()
zscore=stats.zscore(df['Fare'])
threshold=3
zscore_outliers=df[abs(zscore)>threshold]
print("Outliers are :")
print(zscore_outliers)